language: ruby
sudo: false
services:
  - postgresql
before_script:
  - psql  -c "create database datamapper_default_tests;" -U postgres
script: "bundle exec rake spec"
env:
  - "ADAPTER=postgres DM_DB_USER=postgres DM_DB_PASSWORD=''"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
matrix:
  allow_failures:
    - rvm: 2.2.0
